### ISSUE TITLE
bug: don't work in centos 7

### ISSUE THREAD

**Issue by sfordinc** [mattiabasone/tuning-primer#1]
This script don't work in centos 7.
# ./tuning-primer.sh

Using login values from ~/.my.cnf
- INITIAL LOGIN ATTEMPT FAILED -
  Testing for stored webmin passwords:
  None Found
  Could not auto detect login info!
  Found potential sockets: /var/lib/mysql/mysql.sock
  Using: /var/lib/mysql/mysql.sock
  Would you like to provide a different socket?: [y/N] n
  Do you have your login handy ? [y/N] : y
  User: root
  Password: ****

Would you like me to create a ~/.my.cnf file for you? [y/N] : n
- FINAL LOGIN ATTEMPT FAILED -
  Unable to log into socket: /var/lib/mysql/mysql.sock

**Comment by mattiabasone** [comment]
Hi,

Did you find the issue?

**Comment by sfordinc** [comment]
yes. always answer "yes" except for different socket. )))
