### ISSUE TITLE
Doesn't support InnoDB for 10.2

### ISSUE THREAD

**Issue by slarti-b** [mattiabasone/tuning-primer#3]
Found this updated version (thanks!) but we're running MariaDB 10.2 and that isn't supported for the InnoDB checks

**Comment by mattiabasone** [comment]
Thanks! I've changed the check to:

`elif [[ $major_version = 10* ]]`

**Comment by slarti-b** [comment]
Yeah, I was wondering about making it more generic.  Thanks
